# Generated by Django 6.0 on 2026-01-18 21:49

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reply_to', models.CharField(default='', max_length=255)),
                ('state', django_fsm.FSMField(default='pending', max_length=50, protected=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('job_type_name', models.CharField(default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='JobInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
                ('state', django_fsm.FSMField(default='undelivered', max_length=50, protected=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='caroni_agent.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
                ('state', django_fsm.FSMField(default='undelivered', max_length=50, protected=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='caroni_agent.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caroni_agent.jobtype'),
        ),
        migrations.CreateModel(
            name='JobTypeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='caroni_agent.jobtype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_type', 'name'), name='unique_input_name_per_job_type')],
            },
        ),
        migrations.CreateModel(
            name='JobTypeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='caroni_agent.jobtype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_type', 'name'), name='unique_output_name_per_job_type')],
            },
        ),
    ]
