# Generated by Django 6.0 on 2026-01-18 21:36

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(default='pending', max_length=50, protected=True)),
                ('reply_to', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(default='created', max_length=50, protected=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cwl_doc', models.TextField()),
                ('state', django_fsm.FSMField(default='created', max_length=50, protected=True)),
                ('workflow_inputs', models.JSONField(default=dict)),
                ('workflow_outputs', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('cwl_doc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(default='received', max_length=50, protected=True)),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caroni.jobrequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='created', max_length=50, protected=True)),
                ('step_name', models.CharField(default='', max_length=255)),
                ('job_name', models.CharField(default='', max_length=255)),
                ('job_kvs', models.JSONField(default=dict)),
                ('current_job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step', to='caroni.job')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='caroni.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDataflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='awaiting', max_length=50, protected=True)),
                ('src_output_name', models.CharField(default='', max_length=255)),
                ('dst_input_name', models.CharField(default='', max_length=255)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caroni.workflow')),
                ('wfstep_dst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dst_dataflows', to='caroni.workflowstep')),
                ('wfstep_src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src_dataflows', to='caroni.workflowstep')),
            ],
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='caroni.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caroni.workflowtemplate'),
        ),
    ]
