# Generated by Django 6.0 on 2026-01-19 01:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caroni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
