# Generated by Django 6.0 on 2026-01-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caroni', '0002_workflowsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
