# Generated by Django 6.0 on 2026-01-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caroni', '0003_workflowstep_attempts_workflowstep_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdataflow',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
